import { withIds } from "./ids";

export const riddles = withIds(
  [
    {
      question: "Am un butoiaș cu două feluri de vin, care niciodată nu se amestecă.",
      answer: "Oul",
    },
    { question: "Ce trece peste apă și nu se udă?", answer: "Umbra" },
    { question: "Are dinți, dar nu mușcă pe nimeni.", answer: "Pieptenele" },
    { question: "Are ochi, dar nu vede nimic.", answer: "Cartoful" },
    {
      question: "Urcă și coboară toată ziua, dar nu se mișcă din loc.",
      answer: "Scara",
    },
    { question: "Vara se îmbracă, iarna se dezbracă.", answer: "Copacul" },
    { question: "Are gât, dar n-are cap.", answer: "Sticla" },
    { question: "E plin de găuri și totuși ține apa.", answer: "Buretele" },
    { question: "Are frunze, dar nu e copac.", answer: "Cartea" },
    {
      question: "Bate toată ziua și toată noaptea, dar nu supără pe nimeni.",
      answer: "Inima",
    },
    {
      question: "Cu cât iei mai mult din ea, cu atât e mai mare.",
      answer: "Groapa",
    },
    { question: "Merge fără picioare, plânge fără ochi.", answer: "Norul" },
    {
      question: "Cu cât șterge mai mult, cu atât e mai ud.",
      answer: "Prosopul",
    },
    { question: "Are patru picioare și nu merge nicăieri.", answer: "Masa" },
    { question: "Are ace, dar nu coase niciodată.", answer: "Bradul" },
    { question: "Are două limbi și nu spune niciun cuvânt.", answer: "Ceasul" },
    {
      question: "Umblă toată ziua prin oraș, iar seara stă sub pat.",
      answer: "Pantofii",
    },
    { question: "Curge mereu și nu se oprește niciodată.", answer: "Râul" },
    {
      question: "E al tău, dar îl folosesc alții mai des decât tine.",
      answer: "Numele",
    },
    { question: "Cade mereu și nu se lovește niciodată.", answer: "Ploaia" },
    {
      question: "Cu cât e mai mult, cu atât vezi mai puțin.",
      answer: "Întunericul",
    },
    {
      question: "Alb ca zăpada, dulce ca mierea; în ceai dispare.",
      answer: "Zahărul",
    },
    { question: "Îl tai și nu plânge el, ci tu.", answer: "Ceapa" },
    { question: "Are clape, dar nu descuie nicio ușă.", answer: "Pianul" },
    {
      question: "Are orașe, dar nicio casă; are păduri, dar niciun copac.",
      answer: "Harta",
    },
    { question: "Cu cât arde mai mult, cu atât e mai mică.", answer: "Lumânarea" },
    {
      question: "Repetă tot ce spui, dar n-a învățat nicio limbă.",
      answer: "Ecoul",
    },
    { question: "Îl auzi și îl simți, dar nu-l vezi niciodată.", answer: "Vântul" },
    {
      question: "Vara stă la umbră, iarna te ține de cald pe umeri.",
      answer: "Fularul",
    },
    {
      question: "Are coadă, dar nu e animal; zboară, dar n-are aripi.",
      answer: "Zmeul",
    },
    { question: "Nu are mâini, dar deschide și încuie toată casa.", answer: "Cheia" },
    { question: "Trece prin pânză și lasă în urma lui o dâră de ață.", answer: "Acul" },
    { question: "Deschide gura, mușcă hârtia și n-o înghite niciodată.", answer: "Foarfeca" },
    { question: "Te arată exact cum ești și nu ține minte pe nimeni.", answer: "Oglinda" },
    {
      question: "Când plouă se deschide ca o floare, iar pe vreme bună doarme în cui.",
      answer: "Umbrela",
    },
    { question: "Face spumă, spală tot și se micșorează pe zi ce trece.", answer: "Săpunul" },
    { question: "Îți ține capul toată noaptea și nu obosește niciodată.", answer: "Perna" },
    { question: "Are coadă lungă, mănâncă praf prin casă și nu se satură.", answer: "Mătura" },
    { question: "Ajunge la gură de o sută de ori pe zi și nu gustă nimic.", answer: "Lingura" },
    { question: "Stă agățat în tavan și, dintr-o apăsare, face ziuă în casă.", answer: "Becul" },
    { question: "Te primește obosit seara și te lasă odihnit dimineața.", answer: "Patul" },
    { question: "Prin ea intră lumina în casă, dar nu intră nimeni.", answer: "Fereastra" },
    { question: "În burta lui e iarnă chiar și în miezul verii.", answer: "Frigiderul" },
    { question: "O deschizi, o închizi, dar din loc nu pleacă niciodată.", answer: "Ușa" },
    { question: "Se ascute când obosește și lasă pe hârtie un drum negru.", answer: "Creionul" },
    { question: "Șterge greșelile altuia și se face tot mai mică.", answer: "Guma" },
    { question: "Roade creionul și scuipă panglici subțiri de lemn.", answer: "Ascuțitoarea" },
    {
      question: "Stă în spate toată dimineața și duce cărțile în locul tău.",
      answer: "Ghiozdanul",
    },
    { question: "Doi frați rotunzi stau călare pe nas toată ziua.", answer: "Ochelarii" },
    { question: "Sunt două surori la fel, dar una se rătăcește mereu.", answer: "Șosetele" },
    { question: "Are cinci camere și în fiecare stă câte un deget.", answer: "Mănușa" },
    { question: "Are două roți și stă în picioare doar cât timp merge.", answer: "Bicicleta" },
    { question: "Merge pe două linii de fier și fluieră la fiecare gară.", answer: "Trenul" },
    { question: "Cu cât o lovești mai tare, cu atât sare mai sus.", answer: "Mingea" },
    { question: "Merge repede la vale și numai când e zăpadă.", answer: "Sania" },
    { question: "Își poartă casa în spate și ajunge mereu ultimul.", answer: "Melcul" },
    { question: "E mic, plin de ace și se face ghem când se teme.", answer: "Ariciul" },
    { question: "Zboară din floare în floare și duce acasă dulceață.", answer: "Albina" },
    { question: "E cât un bob și duce o povară de zece ori mai mare.", answer: "Furnica" },
    { question: "Țese o plasă fără ac și fără ață.", answer: "Păianjenul" },
    { question: "Sare din iarbă în baltă și cântă acolo toată seara.", answer: "Broasca" },
    { question: "Face un ou pe zi și strigă de parcă ar fi mutat un munte.", answer: "Găina" },
    { question: "N-are ceas și totuși trezește tot satul la timp.", answer: "Cocoșul" },
    { question: "Are mustăți, doarme toată ziua și vede pe întuneric.", answer: "Pisica" },
    { question: "Știe un singur cuvânt și îl latră toată ziua.", answer: "Câinele" },
    { question: "Mănâncă iarbă verde și dă lapte alb.", answer: "Vaca" },
    { question: "Pleacă toamna și se întoarce primăvara la aceeași casă.", answer: "Rândunica" },
    { question: "Tace mereu și nu iese niciodată din apă.", answer: "Peștele" },
    { question: "Adună alune toată toamna și apoi le uită prin pădure.", answer: "Veverița" },
    { question: "A fost omidă, iar acum poartă două aripi ca niște flori.", answer: "Fluturele" },
    { question: "Crește pe cap, îl tai des și tot la loc se face.", answer: "Părul" },
    {
      question: "Stă la mijlocul feței și află primul ce se gătește în bucătărie.",
      answer: "Nasul",
    },
    {
      question: "Sunt zece frați care lucrează împreună și nu se ceartă niciodată.",
      answer: "Degetele",
    },
    { question: "Sunt două, aud tot ce se spune și nu spun nimic.", answer: "Urechile" },
    {
      question: "Cade albă și moale, iar primăvara pleacă fără să spună la revedere.",
      answer: "Zăpada",
    },
    { question: "Răsare fără să bată la ușă și intră la tine pe fereastră.", answer: "Soarele" },
    { question: "Uneori e rotundă ca o farfurie, alteori doar o dungă pe cer.", answer: "Luna" },
    { question: "Se aprind singure seara și nimeni nu le stinge.", answer: "Stelele" },
    { question: "E un pod colorat peste cer, pe care nu trece nimeni.", answer: "Curcubeul" },
    { question: "E apă care s-a făcut sticlă și se topește în palmă.", answer: "Gheața" },
    { question: "Mănâncă lemne toată noaptea și nu se satură.", answer: "Focul" },
    { question: "Curge printre degete ca apa, dar nu udă pe nimeni.", answer: "Nisipul" },
    { question: "Vopsește frunzele în galben și apoi le culcă pe pământ.", answer: "Toamna" },
    { question: "Intră albă în cuptor și iese aurie, cu coajă cu tot.", answer: "Pâinea" },
    { question: "Are casă tare de lemn și un singur locatar înăuntru.", answer: "Nuca" },
    { question: "Se dezbracă de coajă și înăuntru are zece felii dulci.", answer: "Portocala" },
    {
      question: "Verde pe dinafară, roșu pe dinăuntru și plin de sâmburi negri.",
      answer: "Pepenele",
    },
    {
      question: "E dulce și rece, dar dacă stai prea mult la soare, dispare.",
      answer: "Înghețata",
    },
    { question: "Poartă pălărie verde și stă îngropat până la gât.", answer: "Morcovul" },
    {
      question: "E galbenă ca soarele, apoi albă ca puful și pleacă cu vântul.",
      answer: "Păpădia",
    },
  ],
  (item) => item.question
);
