import { withIds } from "./ids";

/** De spus de trei ori, repede. Fraza sub ~95 de caractere, ca să stea mare pe ecran. */
export const tongueTwisters = withIds(
  [
    { text: "Capra calcă piatra, piatra crapă-n patru." },
    { text: "Un vultur stă pe pisc c-un pix în plisc." },
    { text: "Șase sași în șase saci." },
    { text: "Știu că știu că știuca-i știucă și mai știu că știuca-i pește." },
    { text: "Un cocostârc s-a dus să se descocostârcărească." },
    { text: "Am o prepeliță pestriță cu paisprezece pui de prepeliță pestriți." },
    { text: "Domnule Dudău, dă-mi două dude din dudul dumitale." },
    { text: "Rică nu știa să zică râu, rățușcă, rămurică." },
    { text: "Stanca stă-n castan ca Stan." },
    { text: "Pe cap un capac, pe capac un ac." },
    { text: "Bucură-te cum s-a bucurat Bucuroaia de Bucurel bucuros." },
    { text: "Când am zis c-am zis c-oi zice, tot zic eu c-am zis c-oi zice." },
    { text: "Papagalul Panait poartă pălărie portocalie." },
    { text: "Fluturele flutură ușor prin flori de fluturaș." },
    { text: "Papucii lui Popescu pocnesc pe pod, pe pod pocnesc papucii." },
    { text: "Pe prispa pitică, puiul pestriț ciugulește pesmeți presărați." },
    { text: "Patru păpuși poartă pălării pătrate pe podul pictat." },
    { text: "Piticul pistruiat pictează pătrate pe pereții palatului." },
    { text: "Prietenul lui Pavel plimbă patru pisici pe poteca pietruită." },
    { text: "Păunul poartă pene pestrițe, pene pestrițe poartă păunul." },
    { text: "Barbu bate toba, toba bate-n Barbu, Barbu bate bine." },
    { text: "Bobiță numără bob cu bob bobițele din borcanul bunicii." },
    { text: "Bondarul bâzâie-n boschet, boschetul bâzâie de bondari." },
    { text: "Bunica bate blatul în bolul bombat din bucătăria bunicului." },
    { text: "Broscuța brodează o broboadă cu bobițe albastre." },
    { text: "Berbecul bălan behăie blând lângă butucul bătrân." },
    { text: "Cocoșul cocoțat pe coteț cântă, cloșca cotcodăcește-n curte." },
    { text: "Căruța cu covrigi calzi cotește pe cărarea cu castani." },
    { text: "Cocoloașele de cocă se coc încet în cuptorul cu cărămidă." },
    { text: "Un cârd de cârtițe cară cărămizi în cărucioare cârpite." },
    { text: "Croitorul croiește cu cretă cinci cămăși cu cusături curate." },
    { text: "Cucul cucuie-n crâng, crângul cucuie de cuci curioși." },
    { text: "Un cârlionț pe-un cârlig, pe-un cârlig un cârlionț cârlionțat." },
    { text: "Gâsca gâgâie lângă gard, gânsacul gâfâie-n grădină." },
    { text: "Grigore greblează grădina, grădina lui Grigore geme de gărgărițe." },
    { text: "Gugustiucul gungurește pe gard, gardul gungurește de gugustiuci." },
    { text: "Gheorghe ghicește ghicitori ghidușe lângă ghiozdanul lui Ghiță." },
    { text: "Șase șoricei șușotesc sub șura șubredă." },
    { text: "Șaptezeci și șapte de șoareci șed în șaptezeci și șapte de saci." },
    { text: "Sașa așază șase șosete șterse sub scaunul scund." },
    { text: "Sub scara școlii stau șase sănii și șapte schiuri." },
    { text: "Șerpuind, șuvoiul șuieră printre șapte șiruri de sălcii." },
    { text: "Ștefan șterge ștergarul cu șase ștersături scurte." },
    { text: "Sania Sandei stă strâmb sub salcia stufoasă." },
    { text: "O sapă sapă un șanț, șapte sape sapă șapte șanțuri." },
    { text: "Zece zâne zglobii zăresc zmeura zemoasă de pe zid." },
    { text: "Zăvorul zăngănește, zurgălăii zornăie, zăpada zboară zăpăcită." },
    { text: "Zaharia zdrobește zarzavatul, zarzavatul zdrobit zace-n zeamă." },
    { text: "Jenică jonglează jucăuș cu jumătate de jeleu." },
    { text: "Țestoasa țeapănă țopăie tăcut pe țărmul înțesat de țânci." },
    { text: "Țânțarul țiuie, țapul țopăie, țărăncuța țese o țesătură." },
    { text: "Țurțurii se țin țepeni de țeava țuguiată." },
    { text: "Peste țarina țepoasă țopăie țanțoș un țap zburdalnic." },
    { text: "Cinci cinteze ciugulesc cireșe cu ciocuri cioplite." },
    { text: "Cioara cârâie-n cireș, cireșul cârâie de ciori." },
    { text: "Ciocănitoarea ciocănește ciotul, ciotul ciocnește ciocul ciocănitoarei." },
    { text: "Radu rade ridichi rotunde, ridichile rotunde rămân rase." },
    { text: "Roata roșie a ruginit, rugina roade roata roșie." },
    { text: "Rândunica se răsucește rar, rar se răsucește rândunica." },
    { text: "Rareș rupe repede ramuri rare din răchita rărită." },
    { text: "Ruxandra rostogolește roata rotundă prin roua rece a răsăritului." },
    { text: "Trei tigri trec tiptil printre trei trestii tinere." },
    { text: "Dragoș drege drumul drept, drumul drept îl drege Dragoș." },
    { text: "Trandafirul trandafiriu tremură-n tufa tremurândă." },
    { text: "Trenul trece tăcut prin trei tuneluri întortocheate." },
    { text: "Toma taie tăiței tari, tăițeii tari tocesc tăișul." },
    { text: "Doi dulgheri dăltuiesc douăsprezece dulapuri de doi metri." },
    { text: "Domnul Dorel dăruiește douăzeci de dovleci dolofani." },
    { text: "Străbunicul strânge struguri storși pe strada strâmtă." },
    { text: "Scriitorul scrie strâmb, scrisoarea strâmbă strică scrisul." },
    { text: "Scârțâie scara, scârțâie scaunul, scârțâie și scoarța scorușului." },
    { text: "Strugurii strânși de strănepot se strecoară-n strachină." },
    { text: "Scafandrul scoate scoica scumpă din scobitura stâncii." },
    { text: "Sfârâie sfârleaza, sfârleaza sfârâie sfios pe sfoara subțire." },
    { text: "Un strop strălucitor se strecoară printre storurile strânse." },
    { text: "Fetița fluieră fin, fluierul fetiței fluieră și mai fin." },
    { text: "Fasolea fiartă fierbe-n fiertura fierbinte a lui Filip." },
    { text: "Un fir fin de fân firav flutură fără frică." },
    { text: "Fâșâie frunza, foșnește fagul, fâlfâie fluturii fericiți." },
    { text: "Vasilica vâslește vioi, vâslele Vasilicăi vâjâie voios." },
    { text: "Vântul vântură vița, vița vânturată vuiește vioi." },
    { text: "Veverița vioaie vâră vreo nouă nuci în scorbura veche." },
    { text: "Vrabia vrea varză, varza vrea vreme, iar vremea vrea vânt." },
    { text: "Nea Nicu numără nouă nuci noduroase noaptea." },
    { text: "Nu-i noduros nodul? Ba-i noduros nodul din nucul nostru." },
    { text: "Mihai mănâncă mure moi, Marius mestecă mere mari." },
    { text: "Mămăliga Mariei mormăie molcom în micul ceaun." },
    { text: "Melcul molatic merge mărunt pe muchia mesei." },
    { text: "Licuriciul lucește lin lângă lacul limpede." },
    { text: "Lăutarul lălăie lângă lada cu lămâi." },
  ],
  (item) => item.text
);
